SELECT DISTINCT CLIENT.nom, ARTICLE.cod_a, ARTICLE.descrip 
FROM CLIENT, LINIA_FAC, FACTURA, ARTICLE 
WHERE CLIENT.cod_cli=FACTURA.cod_cli AND FACTURA.num_f=LINIA_FAC.num_f AND LINIA_FAC.cod_a=ARTICLE.cod_a 
ORDER BY nom,cod_a ;
