CREATE TABLE VENEDOR
(cod_ven NUMERIC PRIMARY KEY,
nom VARCHAR (100),
adreca VARCHAR (100),
cp NUMERIC,
cod_pob NUMERIC,
cod_cap NUMERIC,
CONSTRAINT cod_pob FOREIGN KEY (cod_pob) REFERENCES PROVINCIA)